version: '3'

services:
  db:
    image: postgres
    container_name: crm-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data